language: go

go:
    - 1.8.x
env:
    - GOARCH=amd64
sudo: false

install:
    - go get github.com/gorilla/websocket

script: mkdir bin && go build -o ./bin/chat ./chat && go test ./trace
notifications:
    email: alanrong@gmail.com
